<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5>Категории каталога</h5>
    </div>
</div>
<!-- /page header -->

<!-- Media datatable Last Orders -->
<div class="widget">
    <div class="navbar-inner">
        <h6>Список категорий</h6>
        <div class="nav pull-right">
            <a href="<?php echo $this->url(array('controller' => 'admin-categories', 'action' => 'add', 'module' => 'shop'), 'default', 'true'); ?>" class="navbar-icon tip" data-original-title="<?php echo $this->translate('add'); ?>">
                <i class="icon-plus"></i>
            </a>
        </div>
    </div>
    <div class="table-overflow">
        <table class="table table-striped table-bordered table-checks">
            <thead>
            <tr>
                <th>#</th>
                <th><?php echo $this->translate('shopCategoryName'); ?></th>
                <th class="actions-column"><?php echo $this->translate('feature');?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->categories as $id => $title) : ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-categories', 'action' => 'edit', 'id' => $id], 'default', true); ?>" title="">
                            <?php echo $id ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-categories', 'action' => 'edit', 'id' => $id], 'default', true); ?>" title=""><?php echo $title; ?></a>
                    </td>
                    <td>
                        <ul class="navbar-icons">
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-categories', 'action' => 'category-products', 'id' => $id], 'default', true); ?>" class="tip" title="<?php echo sprintf($this->translate('shopCategoryProducts'), $title);?>"><i class="icon-folder-open"></i></a></li>
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-categories', 'action' => 'edit', 'id' => $id], 'default', true); ?>" class="tip" title="<?php echo $this->translate('edit');?>"><i class="icon-edit"></i></a></li>
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-categories', 'action' => 'delete', 'id' => $id], 'default', true); ?>" class="tip remove" title="<?php echo $this->translate('remove');?>" ><i class="icon-remove"></i></a></li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!-- /media datatable -->
<script type="text/javascript">
    $('a.remove').click(function () {
        if (!confirm('<?php echo $this->translate("removeHint"); ?>')) {
            return false;
        }
    });
</script>
