<ul class="paginator">
    <?php foreach($this->pagesInRange as $page): ?>
        <?php if($page != $this->current): ?>
            <li> <a class="page-active" href="<?php echo $this->url(array('action' => 'index', 'controller' => 'admin', 'module' => 'news', 'page' => $page), 'default', true); ?>"> <?php echo $page; ?> </a> </li>
        <?php else: ?>
            <li> <p  class="page"> <?php echo $page; ?> </p> </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>