<?php
$prevPage = ($this->current != 1) ? ($this->current - 1) : 1;
$nextPage = ($this->current != count($this->pagesInRange)) ? ($this->current + 1) : count($this->pagesInRange);
?>
<div class="pagination">
    <ul>
        <li>
            <a href="<?php echo $this->url(array('page' => $prevPage), $this->pattern, true); ?>" class="prev">
                <
            </a>
        </li>
        <?php foreach ($this->pagesInRange as $page): ?>
            <li>
                <a href="<?php echo $this->url(array('page' => $page), $this->pattern, true); ?>" class="<?php echo ($page == $this->current) ? 'active' : '';?>">
                    <?php echo $page;?>
                </a>
            </li>
        <?php endforeach;?>
        <li>
            <a href="<?php echo $this->url(array('page' => $nextPage), $this->pattern, true); ?>" class="next">
                >
            </a>
        </li>
    </ul>
</div>
