DROP TABLE IF EXISTS `Partners`;
CREATE TABLE `Partners` (
  `id` int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(250) NOT NULL,
  `photo` VARCHAR(250) NOT NULL,
  `url` VARCHAR(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
