<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <?php if ('add' == $this->action) { ?>
            <h5>Добавление номера</h5>
        <?php } else { ?>
            <h5>Редактирование номера</h5>
        <?php } ?>
    </div>
</div>

<h5 class="widget-name"></h5>

<div class="widget row-fluid">
    <div class="well span16">
        <div class="form-overflow">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    CKEDITOR.replace('shortDescription');
    CKEDITOR.replace('description');
</script>