<?php
    $param = Zend_Controller_Front::getInstance()->getRequest()->getParam('catalogId', 0);
?>
<?php foreach ($this->items as $item) : ?>
<div class="menu-block">
  <div class="title" id="label<?php echo $item['id'];?>"><?php echo $item['title']; ?></div>
  <ul class="menu" id="menu-label<?php echo $item['id']; ?>">
    <?php foreach ($item['items'] as $portfolio) : ?>
    <li><a href="<?php echo $this->url(array('catalogId' => $item['id'], 'itemId' => $portfolio['id']), '/portfolio', true); ?>"><?php echo $portfolio['title']; ?></a></li>
    <?php endforeach; ?>
  </ul>
</div>
<?php endforeach; ?>

