<div class="portfolio_item col-lg-4 col-md-6 col-sm-12 col-12">
    <div class="portfolio_photo">
        <a href="<?php echo $this->url(['controller' => 'index', 'action' => 'portfolio-example', 'module'=> 'portfolio', 'portfolioId' => $this->mainImage[0]['portfolioId']], 'default', true);?>">
            <img class="" src="<?php echo $this->baseUrl() . '/' . ($this->mainImage[0]['image']);?>" alt="Квартира"/>
        </a>
    </div>
</div>

