<?php foreach ($this->rooms as $room) { ?>
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <div class="room-list-item">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12">
                    <div class="image">
                        <a href="<?php echo $this->url(['alias' => $room['alias']], '/apartmentsShow', true);?>">
                            <img src="<?php echo $this->baseUrl() .'/' . $this->hotelRoomImage($room['photo']); ?>" class="img-responsive" />
                            <span>
                                <div class="person">
                                    <img src="<?php echo $this->baseUrl();?>/img/person.png" /> <?php echo $room['personAmount']; ?>
                                </div>
                                <ul class="room-services">
                                    <?php if ($room['bed']) : ?>
                                        <li class="bed">Двухместная кровать</li>
                                    <?php endif;?>
                                    <?php if ($room['shower']) : ?>
                                        <li class="shower">Душ</li>
                                    <?php endif;?>
                                    <?php if ($room['wifi']) : ?>
                                        <li class="wifi">Wi-Fi</li>
                                    <?php endif;?>
                                    <?php if ($room['jacuzzi']) : ?>
                                        <li class="jacusi">Джакузи</li>
                                    <?php endif;?>
                                    <?php if ($room['fridge']) : ?>
                                        <li class="fridge">Холодильник</li>
                                    <?php endif;?>
                                    <?php if ($room['fireplace']) : ?>
                                        <li class="fireplace">Камин</li>
                                    <?php endif;?>
                                </ul>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12">
                    <div class="title">
                        <a href="<?php echo $this->url(['alias' => $room['alias']], '/apartmentsShow', true);?>">
                            <?php echo $room['title']; ?>
                        </a>
                    </div>
                    <div class="description">
                        <?php echo $room['shortDescription']; ?>
                    </div>
                    <div class="price">
                        Цена за сутки: <span><?php echo $room['pricePerDay']; ?><span>Руб</span></span>
                    </div>
                    <div class="buttons">
                        <a href="<?php echo $this->url(['alias' => $room['alias']], '/apartmentsShow', true);?>" class="btn btn-room-page">Подробнее</a><a href="#" class="btn btn-room-booking" data-id="<?php echo $room['id'];?>">Забронировать</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>
