<!-- Booking Modal -->
<div class="modal fade" id="bookingModal" tabindex="-1" role="dialog" aria-labelledby="bookingModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="bookingModalLabel">Забронировать номер</h4>
            </div>
            <div class="modal-body">
                <?php echo $this->form;?>
                <div id="booking-common-error" class="booking-form-error">

                </div>
            </div>
        </div>
    </div>
</div>
