<section class="room-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Заявка принята</h1>
                <div class="header_decorator">
                    <img src="<?php echo $this->baseUrl();?>/img/header_decorator.png" class="img-responsive" />
                </div>
            </div>
            <div class="col-lg-12">
                <p>
                    Ваша заявка принята. Наш менеджер свяжется с Вами в ближайщее время.
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />

                    <br />
                    <br />
                    <br />
                    <br />
                </p>
            </div>
        </div>
    </div>
</section>