<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5><?php echo $this->translate('userEditForm'); ?></h5>
        <span></span>    
    </div>
</div>
<!-- /page header -->
<!-- Page form -->
<h5 class="widget-name"></h5>

<div class="widget row-fluid">
    <div class="well span10">
        <div class="form-overflow">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<!-- /Page form -->