<div class="row static">
    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 header">
        <h2><?php echo $this->product->title;?></h2>
    </div>
    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12 main-content">
        <div class="static product-content">
            <div class="left">
                <div class="producer">
                    <span><?php echo $this->category->title;?></span> Категория
                </div>
                <div class="desc">
                    <?php echo $this->product->description;?>
                </div>
                <div class="props-and-price">
                    <div class="left">
                        <h4>Характеристики</h4>
                        <ul class="product-properties">
                            <?php foreach ($this->productFilters as $value => $title) : ?>
                            <li>
                                <label><?php echo $title;?>:</label> <?php echo $value;?>
                            </li>
                            <?php endforeach; ?>

                        </ul>
                    </div>
                    <div class="right">
                        <div class="price">
                            <?php echo $this->product->price;?> <span class="glyphicon glyphicon-rub"></span>
                        </div>
                        <div class="amount-and-cart">
                            <div class="product-amount-changer">
                                <div class="minus" id="product-info-minus">-</div>
                                <div class="amount">
                                    <input type="text" value="1" name="product-amount" id="product-info-amount" />
                                </div>
                                <div class="plus" id="product-info-plus">+</div>
                            </div><div class="add-to-cart" data-id="<?php echo $this->product->id;?>" data-amount="1" id="product-info-btn">
                                Купить сейчас
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="right">
                <img src="<?php echo $this->baseUrl() . '/' . $this->productImage($image['image']);?>" alt="" />
                <div class="stickers">
                    <?php if ($this->product->sale == 1) : ?>
                        <div class="sale">Распродажа</div>
                    <?php endif ;?>
                    <?php if ($this->product->new == 1) : ?>
                        <div class="new">Новинка</div>
                    <?php endif ;?>
                </div>
            </div>
        </div>
    </div>
</div>

