<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5><?php echo $this->translate('shopProducts');?></h5>
    </div>
</div>
<!-- /page header -->

<!-- Media datatable Last Orders -->
<div class="widget">
    <div class="navbar-inner">
        <h6><?php echo $this->translate('shopProductsList');?></h6>
        <div class="nav pull-right">
            <a href="<?php echo $this->url(array('controller' => 'admin-products', 'action' => 'add', 'module' => 'shop'), 'default', 'true'); ?>" class="navbar-icon tip" data-original-title="<?php echo $this->translate('add'); ?>">
                <i class="icon-plus"></i>
            </a>
        </div>
    </div>
    <div class="table-overflow">
        <table class="table table-striped table-bordered table-checks">
            <thead>
            <tr>
                <th>#</th>
                <th><?php echo $this->translate('adminTitle'); ?></th>
                <th><?php echo $this->translate('shopCategoryName'); ?></th>
                <th><?php echo $this->translate('adminPrice'); ?></th>
                <th class="actions-column"><?php echo $this->translate('feature');?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->products as $item) : ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-products', 'action' => 'edit', 'id' => $item['productId']], 'default', true); ?>" title=""><?php echo $item['productId']; ?></a>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-products', 'action' => 'edit', 'id' => $item['productId']], 'default', true); ?>" title=""><?php echo $item['productTitle']; ?></a>
                    </td>
                    <td>
                        <?php echo $item['category'] ?>
                    </td>
                    <td>
                        <?php echo $item['productPrice'] ?>
                    </td>
                    <td>
                        <ul class="navbar-icons">
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-products', 'action' => 'product-images', 'id' => $item['productId']], 'default', true); ?>" class="tip" title="<?php echo $this->translate('images');?>"><i class="icon-picture"></i></a></li>
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-products', 'action' => 'product-properties', 'id' => $item['productId']], 'default', true); ?>" class="tip" title="<?php echo $this->translate('properties');?>"><i class="icon-list"></i></a></li>
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-products', 'action' => 'edit', 'id' => $item['productId']], 'default', true); ?>" class="tip" title="<?php echo $this->translate('edit');?>"><i class="icon-edit"></i></a></li>
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-products', 'action' => 'delete', 'id' => $item['productId']], 'default', true); ?>" class="tip remove" title="<?php echo $this->translate('remove');?>" ><i class="icon-remove"></i></a></li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'admin-pagination.phtml', array('pattern' => array('action' => 'index', 'controller' => 'admin-products', 'module' => 'shop'))); ?>
    </div>
</div>
<!-- /media datatable -->
<script type="text/javascript">
    $('a.remove').click(function () {
        if (!confirm('<?php echo $this->translate("removeProductHint"); ?>')) {
            return false;
        }
    });
</script>