<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5><?php echo $this->translate('shopProductImages');?></h5>
    </div>
</div>
<!-- /page header -->

<!-- Media datatable Last Orders -->
<div class="widget">
    <div class="navbar-inner">
        <h6><?php echo $this->translate('shopProductImagesList');?></h6>
        <div class="nav pull-right">
            <a href="<?php echo $this->url(array('controller' => 'admin-products', 'action' => 'add-product-image', 'module' => 'shop', 'id' => $this->product->id), 'default', 'true'); ?>" class="navbar-icon tip" data-original-title="<?php echo $this->translate('add'); ?>">
                <i class="icon-plus"></i>
            </a>
        </div>
    </div>
    <div class="table-overflow">
        <table class="table table-striped table-bordered table-checks">
            <thead>
            <tr>
                <th>#</th>
                <th><?php echo $this->translate('productImage'); ?></th>
                <th class="actions-column"><?php echo $this->translate('feature');?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->images as $item) : ?>
                <tr>
                    <td>

                    </td>
                    <td>
                        <img class="product-image" src="<?php echo $this->baseUrl() . DIRECTORY_SEPARATOR . $this->productImage($item['image']);?>" />
                    </td>
                    <td>
                        <ul class="navbar-icons">
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-products', 'action' => 'delete-product-image', 'id' => $this->product->id, 'imageId' => $item['id']], 'default', true); ?>" class="tip remove" title="<?php echo $this->translate('remove');?>" ><i class="icon-remove"></i></a></li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!-- /media datatable -->
<script type="text/javascript">
    $('a.remove').click(function () {
        if (!confirm('<?php echo $this->translate("removeProductImageHint"); ?>')) {
            return false;
        }
    });
</script>