<!DOCTYPE HTML>

<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>
<head>
    <?php echo $this->headMeta(); ?>

    <link rel='icon' type='image/png' href='<?php echo $this->baseUrl(); ?>/images/favicon.png'></link>
    <link type='text/css' rel='stylesheet' href='<?php echo $this->baseUrl(); ?>/css/error.css'></link>

    <?php echo $this->headTitle(); ?>
</head>
<body>
    <?php echo $this->layout()->content; ?>
</body>
</html>