<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5><?php echo $this->translate('adminFilters');?></h5>
    </div>
</div>
<!-- /page header -->

<!-- Media datatable Last Orders -->
<div class="widget">
    <div class="navbar-inner">
        <h6><?php echo $this->translate('shopFiltersList');?></h6>
        <div class="nav pull-right">
            <a href="<?php echo $this->url(array('controller' => 'admin-filters', 'action' => 'add', 'module' => 'shop'), 'default', 'true'); ?>" class="navbar-icon tip" data-original-title="<?php echo $this->translate('add'); ?>">
                <i class="icon-plus"></i>
            </a>
        </div>
    </div>
    <div class="table-overflow">
        <table class="table table-striped table-bordered table-checks">
            <thead>
            <tr>
                <th class="small">#</th>
                <th><?php echo $this->translate('shopFilterTitle');?></th>
                <th class="actions-column"><?php echo $this->translate('feature');?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->paginator as $item) : ?>
                <tr>
                    <td><?php echo $item['id'];?></td>
                    <td>
                        <a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-filters', 'action' => 'edit', 'id' => $item['id']], 'default', true); ?>" title=""><?php echo $item['title']; ?></a>
                    </td>
                    <td>
                        <ul class="navbar-icons">
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-filters', 'action' => 'filter-elements-list', 'id' => $item['id']], 'default', true); ?>" class="tip" title="<?php echo sprintf($this->translate('shopFilterElements'), $item['title']);?>"><i class="icon-folder-open"></i></a></li>
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-filters', 'action' => 'edit', 'id' => $item['id']], 'default', true); ?>" class="tip" title="<?php echo $this->translate('edit');?>"><i class="icon-edit"></i></a></li>
                            <li><a href="<?php echo $this->url(['module' => 'shop', 'controller' => 'admin-filters', 'action' => 'delete', 'id' => $item['id']], 'default', true); ?>" class="tip remove" title="<?php echo $this->translate('remove');?>" ><i class="icon-remove"></i></a></li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'admin_pagination.phtml', array('pattern' => array('action' => 'index', 'controller' => 'admin-filters', 'module' => 'shop'))); ?>
    </div>
</div>
<!-- /media datatable -->
<script type="text/javascript">
    $('a.remove').click(function () {
        if (!confirm('<?php echo $this->translate("removeFilterHint"); ?>')) {
            return false;
        }
    });
</script>
