<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5>
	  <?php if (0 != $this->parent) : ?>
	  <?php echo sprintf($this->translate('servicesAdminCategoryList'), $this->categoryTitle); ?>
	  <?php else : ?>
	  <?php echo sprintf($this->translate('servicesAdminCategoryMain'), $this->categoryTitle); ?>
	  <?php endif;?>
	</h5>
        <span>
	  <br />
	  <?php if (0 != $this->parent) : ?>
	  <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index', 'module'=> 'services','parent' => $this->parentCategoryId), 'default', true);?>" class="btn btn-primary">
	    <?php echo sprintf($this->translate('servicesCategoryBackCategory'), $this->categoryTitle);?>
	  </a>
	  <?php endif;?>
	</span>
    </div>
</div>
<!-- /page header -->

<h5 class="widget-name"></h5>

<!-- Media datatable Last Orders -->
<div class="widget">
    <div class="navbar">
        <div class="navbar-inner">
            <h6><?php echo $this->translate('servicesCategoryList'); ?></h6>
            <?php if((int)$this->parent === 0) : ?>
            <div class="nav pull-right">
                <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'add-category', 'module' => 'services'), 'default', 'true'); ?>"
                   class="navbar-icon tip" data-original-title="<?php echo $this->translate('servicesCategoryAdd'); ?>">
                    <i class="icon-plus"></i>
                </a>
            </div>
            <?php endif; ?>
        </div>
    </div>
    <div class="table-overflow">
        <table class="table table-hover">
            <thead>
            <tr>
                <th><?php echo $this->translate('servicesName'); ?></th>
                <th><?php echo $this->translate('servicesAlias'); ?></th>
                <th class="actions-column-wide"><?php echo $this->translate('servicesAction');?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->categories as $category) : ?>
                <tr>
                    <td>
                        <?php if ((int)$category['subcategories'] === 1) : ?>
                        <a href="<?php echo $this->url(array('module' => 'services', 'controller' => 'admin', 'action' => 'index', 'parent' => $category['id']), 'default', true);?>"><?php echo $category['title'];?></a>
                        <?php elseif (((int)$category['services'] === 1)) : ?>
                        <a href="<?php echo $this->url(array('module' => 'services', 'controller' => 'admin', 'action' => 'list-services', 'category' => $category['id']), 'default', true);?>"><?php echo $category['title'];?></a>
                        <?php else : ?>
                        <?php echo $category['title'];?>
                        <?php endif;?>
                    </td>
                    <td>
                        <?php echo $category['alias']; ?>
                    </td>
                    <td>
                        <ul class="table-controls">
                            <?php if ((int)$category['services'] === 1) : ?>
                                <li>
                                    <a class="btn tip disabled">
                                        <i class="icon-plus"></i>
                                    </a>
                                </li>
                            <?php else : ?>
                                <li>
                                    <a href="<?php echo $this->url(array('action' => 'add-category', 'controller' => 'admin', 'module' => 'services', 'parent' => $category['id']), 'default', true); ?>"
                                       class="btn tip" title="" data-original-title="<?php echo $this->translate('servicesCategoryAddSub'); ?>">
                                        <i class="icon-plus"></i>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ((int)$category['subcategories'] === 1) : ?>
                                <li>
                                    <a class="btn tip disabled">
                                        <i class="icon-plus"></i>
                                    </a>
                                </li>
                            <?php else : ?>
                                <li>
                                    <a href="<?php echo $this->url(array('action' => 'add-service', 'controller' => 'admin', 'module' => 'services', 'category' => $category['id']), 'default', true); ?>"
                                       class="btn tip" title="" data-original-title="<?php echo $this->translate('servicesAdd'); ?>">
                                        <i class="icon-plus"></i>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <li>
                                <a href="<?php echo $this->url(array('action' => 'edit-category', 'controller' => 'admin', 'module' => 'services', 'id' => $category['id'], 'parent' => $this->parent), 'default', true); ?>"
                                   class="btn tip" title="" data-original-title="<?php echo $this->translate('servicesCategoryEdit'); ?>">
                                    <i class="icon-pencil"></i>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array('action' => 'remove-category', 'controller' => 'admin', 'module' => 'services', 'id' => $category['id'], 'parent' => $this->parent), 'default', true); ?>"
                                   class="btn tip" title="" data-original-title="<?php echo $this->translate('servicesCategoryDelete'); ?>"
                                   onclick="<?php echo "return confirm('{$this->translate('servicesCategoryDeleteConfirm')}')"; ?>">
                                    <i class="icon-trash"></i>
                                </a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!-- /media datatable -->
