<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5><?php echo $this->translate( 'showTrxHistoryPageTitle' ); ?></h5>
        <span><?php echo $this->translate( 'showTrxHistoryPageTitleSpan' ); ?></span>
    </div>
</div>

<h5 class="widget-name"></h5>

<div class="widget">
    <div class="navbar">
        <div class="navbar-inner">
            <h6><?php echo $this->translate( 'showTrxHistoryNavbarTitle' ); ?></h6>
        </div>
    </div>
    <div class="table-overflow">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th><?php echo $this->translate( 'id' ); ?></th>
                    <th><?php echo $this->translate( 'type' ); ?></th>
                    <th><?php echo $this->translate( 'user' ); ?></th>
                    <th><?php echo $this->translate( 'amount' ); ?></th>
                    <th><?php echo $this->translate( 'orderId' ); ?></th>
                    <th><?php echo $this->translate( 'deliveryId' ); ?></th>
                    <th><?php echo $this->translate( 'trxId' ); ?></th>
                    <th><?php echo $this->translate( 'bankTs' ); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ( $this->paginator as $item ) : ?>
                    <tr>
                        <td><?php echo $item[ 'id' ]; ?></td>
                        <td>
                            <?php
                                if ($item['type'] == 'add') {
                                    // add balance
                                    if (!empty($item['orderId'])) {
                                        echo $this->translate('historyInfoOrderAdd') . $item['orderId'];
                                    } elseif (empty($item['trxId'])) {
                                        echo $this->translate('historyInfoAdminAdd');
                                    } else {
                                        echo $this->translate('historyInfoUserAdd');
                                    }
                                } elseif ($item['type'] == 'dec') {
                                    // delivery
                                    if (
                                            !empty($item['deliveryId']) && empty($item['trxId'])
                                    ) {
                                        echo $this->translate('historyInfoDeliveryDecBalance') . $item['deliveryId'];
                                    } elseif (
                                            !empty($item['deliveryId']) && !empty($item['trxId'])
                                    ) {
                                        echo $this->translate('historyInfoDeliveryDecOnline') . $item['deliveryId'];
                                    }
                                    // order
                                    if (
                                            !empty($item['orderId']) && empty($item['trxId'])
                                    ) {
                                        echo $this->translate('historyInfoOrderDecBalance') . $item['orderId'];
                                    } elseif (
                                            !empty($item['orderId']) && !empty($item['trxId'])
                                    ) {
                                        echo $this->translate('historyInfoOrderDecOnline') . $item['orderId'];
                                    }
                                    // admin
                                    if (
                                            empty($item['trxId']) && empty($item['orderId']) && empty($item['deliveryId'])
                                    ) {
                                        echo $this->translate('historyInfoAdminDec');
                                    }
                                } elseif ($item['type'] == 'hold-add') {
                                    // order
                                    if (
                                            !empty($item['orderId']) && empty($item['trxId'])
                                    ) {
                                        echo $this->translate('historyInfoOrderHoldAddBalance') . $item['orderId'];
                                    } elseif (
                                            !empty($item['orderId']) && !empty($item['trxId'])
                                    ) {
                                        echo $this->translate('historyInfoOrderHoldAddOnline') . $item['orderId'];
                                    }
                                } elseif ($item['type'] == 'hold-dec') {
                                    // order
                                    if (
                                            !empty($item['orderId']) && empty($item['trxId'])
                                    ) {
                                        echo $this->translate('historyInfoOrderHoldDecBalance') . $item['orderId'];
                                    } elseif (
                                            !empty($item['orderId']) && !empty($item['trxId'])
                                    ) {
                                        echo $this->translate('historyInfoOrderHoldDecOnline') . $item['orderId'];
                                    }
                                } elseif ($item['type'] == 'order') {
                                    echo $this->translate('historyInfoOrderOrder') . $item['orderId'];
                                }
                            ?>
                        </td>
                        <td>
                            <b><?php echo $this->translate( 'fio' ); ?></b>: <?php echo $item[ 'userFio' ] ? $item[ 'userFio' ] : '-'; ?>
                            <br>
                            <b><?php echo $this->translate( 'email' ); ?></b>: <?php echo $item[ 'userEmail' ] ? $item[ 'userEmail' ] : '-'; ?>
                        </td>
                        <td><?php echo $item[ 'amount' ]; ?></td>
                        <td><?php echo isset( $item[ 'orderId' ] ) ? $item[ 'orderId' ] : ' - '; ?></td>
                        <td><?php echo isset( $item[ 'deliveryId' ] ) ? $item[ 'deliveryId' ] : ' - '; ?></td>
                        <td><?php echo isset( $item[ 'trxId' ] ) ? $item[ 'trxId' ] : ' - '; ?></td>
                        <td><?php echo isset( $item[ 'ts' ] ) ? $item[ 'ts' ] : ' - '; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl( $this->paginator, 'Sliding', 'admin_history_pagination.phtml' ); ?>
    </div>
</div>