<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5>Категории номеров</h5>
    </div>
</div>
<!-- /page header -->

<h5 class="widget-name"></h5>

<!-- Media datatable Last Orders -->
<div class="widget">
    <div class="navbar">
        <div class="navbar-inner">
            <h6>Список категорий</h6>
            <div class="nav pull-right">
                <a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'add', 'module' => 'hotelrooms'), 'default', 'true'); ?>"
                   class="navbar-icon tip" data-original-title="Добавить">
                    <i class="icon-plus"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="table-overflow">
        <table class="table table-hover">
            <thead>
            <tr>
                <th class="small">#</th>
                <th>Название</th>
                <th class="actions-column">Действия</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->paginator as $item) : ?>
                <tr>
                    <td>
                        <?php echo $item['position']; ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array('action' => 'edit', 'controller' => 'admin', 'module' => 'hotelrooms', 'id' => $item['id']), 'default', true); ?>" title="">
                            <?php echo $item['title']; ?>
                        </a>
                    </td>
                    <td>
                        <ul class="table-controls">
                            <li>
                                <a href="<?php echo $this->url(array('action' => 'index', 'controller' => 'admin-room', 'module' => 'hotelrooms', 'categoryId' => $item['id']), 'default', true); ?>"
                                   class="btn tip" title="" data-original-title="Номера">
                                    <i class="icon-building"></i>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array('action' => 'edit', 'controller' => 'admin', 'module' => 'hotelrooms', 'id' => $item['id']), 'default', true); ?>"
                                   class="btn tip" title="" data-original-title="Редактировать">
                                    <i class="icon-pencil"></i>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url(array('action' => 'delete', 'controller' => 'admin', 'module' => 'hotelrooms', 'id' => $item['id']), 'default', true); ?>"
                                   class="btn tip delete" title="" data-original-title="Удалить">
                                    <i class="icon-trash"></i>
                                </a>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'admin-pagination.phtml', array('pattern' => array('action' => 'index', 'controller' => 'admin', 'module' => 'hotelrooms'))); ?>
    </div>
</div>
<!-- /media datatable -->

<script type="text/javascript">
    $('.delete').click(function () {
        return confirm('Вы уверены, что хотите удалить запись?');
    })
</script>