<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5><?php echo $this->translate('socialNetworksForm'); ?></h5>
        <span></span>
    </div>
</div>
<!-- /page header -->

<h5 class="widget-name"></h5>

<!-- Media datatable Last Orders -->
<div class="widget row-fluid">

</div>
<!-- /media datatable -->

<!-- Media datatable Last Orders -->
<div class="widget row-fluid">
    <div class="well span8">
        <div class="form-overflow">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<!-- /media datatable -->