<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <?php if ('add' == $this->action) { ?>
            <h5><?php echo $this->translate('addingNewsPageTitle'); ?></h5>
            <span><?php echo $this->translate('addingNewsPageTitleSpan'); ?></span>
        <?php } else { ?>
            <h5><?php echo $this->translate('editingNewsPageTitle'); ?></h5>
            <span><?php echo $this->translate('editingNewsPageTitleSpan'); ?></span>
        <?php } ?>
    </div>
</div>

<h5 class="widget-name"></h5>

<div class="widget row-fluid">
    <div class="well span16">
        <div class="form-overflow">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    CKEDITOR.replace('newsDescription');
    CKEDITOR.replace('newsContent');
    $("#newsDate").datepicker();
</script>
