<h1> <?php echo $this->title == '' ? $this->translate('changePassword') : $this->title; ?> </h1>

<div class="registration">   
	<form method="post" action class="form-horizontal reg-form">
		<?php echo $this->form->password; ?>
		<?php echo $this->form->confirm; ?>
		<div class="form-group seperator"></div>
		<?php echo $this->form->submit; ?>
	</form>
</div>
<?php echo $this->action('oferta', 'index', 'default'); ?>

<script type="text/javascript">
    $(document).ready(function() {
    $('#refresh').click(function() { 
        $.ajax({ 
            url: '<?php echo $this->baseUrl(); ?>/user/registration/refresh-captcha', 
            dataType:'json', 
            success: function(data) { 
                $('.form-captcha-row img').attr('src', data.src); 
                $('#captcha-id').attr('value', data.id); 
            }
        }); 
    }); 
});
</script>