<div class="row featured-boxes login">
  <div class="col-sm-16">
    <div class="featured-box featured-box-secundary default info-content">
      <div class="box-content">
        <h2>
          <?php echo $this->translate('userRegisterSuccessTitle');?>
        </h2>
        <p>
          <?php echo $this->translate('userRegisterSuccessDescription'); ?>
        </p>
      </div>
    </div>
  </div>
</div>
