<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5><?php echo $this->translate('editEmailSettings'); ?></h5>
        <span></span>
    </div>
</div>
<!-- /page header -->

<h5 class="widget-name"></h5>

<!-- Media datatable Last Orders -->
<div class="widget row-fluid">
    <a class="alert alert-info" href="<?php echo $this->url(array('controller' => 'mail', 'action' => 'check-email-connection', 'module' => 'admin')); ?>"><?php echo $this->translate('checkEmailSettings'); ?></a>
</div>
<!-- /media datatable -->

<!-- Media datatable Last Orders -->
<div class="widget row-fluid">
    <div class="well span8">
        <div class="form-overflow">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<!-- /media datatable -->