<?php $translate = Zend_Registry::get('Root_Translate'); ?>
<?php if (isset($this->pattern)) : ?>
<div class="table-footer">
    <div class="pagination">
        <ul>
            <li>
                <a href="<?php echo $this->pattern . '/page/' . (($this->currentPage > 1) ? $this->currentPage - 1 : 1); ?>"><?php echo $translate->_('pagePrev'); ?></a>
            </li>
            <?php foreach($this->pagesInRange as $page): ?>
                <?php if($page != $this->current): ?>                
                    <li><a href="<?php echo $this->pattern . '/page/' . $page; ?>"><?php echo $page; ?></a></li>
                <?php else : ?>
                    <li class="active"><a href="<?php echo $this->pattern . '/page/' . $page; ?>"><?php echo $page; ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
            <li><a href="<?php echo $this->pattern . '/page/' . (($this->currentPage < count($this->pagesInRange) ? $this->currentPage + 1 : count($this->pagesInRange))); ?>"><?php echo $translate->_('pageNext'); ?></a></li>
        </ul>
    </div>
</div> 
<?php endif; ?>