<!-- Page header -->
<div class="page-header row-fluid">
    <div class="page-title span8">
        <h5><?php echo $this->translate('adminImport'); ?></h5>
        <span><?php echo $this->translate('adminImportDescription'); ?></span>
    </div>
</div>

<div class="widget row-fluid">
    <div class="well span8">
        <div class="form-overflow">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>

<span class="lastdate"><?php echo $this->translate('adminLastUpdate').$this->lastDate; ?></span>
