<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5><?php echo $this->translate('faqsList'); ?></h5>
        <span><?php echo ''; ?></span>
    </div>
</div>
<!-- /page header -->

<h5 class="widget-name"></h5>

<!-- Media datatable Last Orders -->
<div class="widget">
    <div class="navbar">
        <div class="navbar-inner">
            <h6><?php echo $this->translate('faqsList'); ?></h6>
        </div>
    </div>
    <div class="table-overflow">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="small"><?php echo $this->translate('id'); ?></th>
                    <th><?php echo $this->translate('faq'); ?></th>
                    <th class="small"><?php echo $this->translate('date'); ?></th> 
                    <th class="small"><?php echo $this->translate('show'); ?></th> 
                    <th class="actions-column"><?php echo $this->translate('actions'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->faqs as $faq) : ?>
                    <tr>
                        <td><?php echo $faq['id']; ?></td>
                        <td>
                            <a href="<?php echo $this->url(array('action' => 'reply', 'controller' => 'admin', 'module' => 'faq', 'id' => $faq['id']), 'default', true); ?>" title="">
                                <?php echo $faq['question']; ?>
                            </a>
                        </td>
                        <td><?php echo date('d.m.Y', strtotime($faq['questionDate'])); ?></td>
                        <td><?php echo ($faq['show']) ? $this->translate('showYes') : $this->translate('showNo'); ?></td>
                        <td>
                            <ul class="table-controls">
                                <li>
                                    <a href="<?php echo $this->url(array('action' => 'reply', 'controller' => 'admin', 'module' => 'faq', 'id' => $faq['id']), 'default', true); ?>"
                                       class="btn tip" title="" data-original-title="<?php echo $this->translate('reply'); ?>">
                                        <i class="icon-reply"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url(array('action' => 'delete', 'controller' => 'admin', 'module' => 'faq', 'id' => $faq['id']), 'default', true); ?>"
                                       class="btn tip" title="" data-original-title="<?php echo $this->translate('delete'); ?>"
                                       onclick="<?php echo "return confirm('{$this->translate('faqDeleteConfirm')}')"; ?>">
                                        <i class="icon-trash"></i>
                                    </a>
                                </li>
                            </ul>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'admin_pagination.phtml', array('pattern' => array('action' => 'index', 'controller' => 'admin', 'module' => 'faq'))); ?>
    </div>
</div>
<!-- /media datatable -->