<section id="achievments" >
    <div class="container">
        <div class="row justify-content-around">
            <div class="achiev_block">
                <div class="image_content d-flex"><img class="align-bottom"
                                                       src="<?php echo $this->baseUrl(); ?>/img/achievments/achiev_list.svg"></div>
                <div class="text">Нам доверяют <b>30</b> крупных компаний</div>
            </div>
            <div class="achiev_block">
                <div class="image_content d-flex"><img class="align-bottom"
                                                       src="<?php echo $this->baseUrl(); ?>/img/achievments/achiev_plan.svg"></div>
                <div class="text">У нас на счету более <b>400</b> довольных клиентов</div>
            </div>
            <div class="achiev_block">
                <div class="image_content d-flex"><img class="align-bottom"
                                                       src="<?php echo $this->baseUrl(); ?>/img/achievments/achiev_gear.svg"></div>
                <div class="text">О нас написали более <b>200</b> положительных отзывов</div>
            </div>
            <div class="achiev_block">
                <div class="image_content d-flex"><img class="align-bottom"
                                                       src="<?php echo $this->baseUrl(); ?>/img/achievments/achiev_house.svg"></div>
                <div class="text">Мы входим в топ <b>10</b> строительных компаний города</div>
            </div>
        </div>
    </div>
</section>