<div id="callus_pages">
    <div class="container">
        <div class="row">
            <div id="callus_form_pages" class="offset-lg-1 col-lg-4 offset-md-2 col-md-8 offset-sm-1 col-sm-10 offset-1 col-10">
                <div class="formheader">
                    <b>Оставьте заявку</b><br>
                    <small><small>наш менеджер перезвонит вам в течении 20 минут</small></small>
                </div>
                <form>
                    <div class="form-group">
                        <input type="text" class="form-control" id="nameInput" aria-describedby="name" placeholder="Имя" required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="phoneInput" placeholder="Телефон" required>
                    </div>
                    <button id="callus_pages_button" type="reset" class="main_button">Отправить</button>
                </form>
            </div>
            <img class="offset-lg-1 col-lg-5 d-lg-block d-md-none d-sm-none d-none" src="<?php echo $this->baseUrl(); ?>/img/builder.png">
        </div>
    </div>
</div>