<?php $translate = Zend_Registry::get('Root_Translate'); ?>
<div class="contact-details">
    <h4><?php echo $translate->_('contacts'); ?></h4>
    <ul class="contact">
        <li><p><i class="fa fa-map-marker"></i> <strong><?php echo $translate->_('address'); ?>:</strong> <?php echo $this->contacts['address']?></p></li>
        <li><p><i class="fa fa-phone"></i> <strong><?php echo $translate->_('phone'); ?>:</strong> <?php echo $this->contacts['phone']?></p></li>
        <li><p><i class="fa fa-envelope"></i> <strong><?php echo $translate->_('email'); ?>:</strong> <a href="mailto:<?php echo $this->contacts['email']?>"><?php echo $this->contacts['email']?></a></p></li>
    </ul>
</div>
