<footer>
    <div class="container">
        <div class="row">
            <div class="logo col-lg-2 col-md-4 d-lg-block d-md-block d-sm-none d-none">
                <img src="<?php echo $this->baseUrl(); ?>/img/footer_logo.png" alt="Логотип Чиним Строим" class="img-responsive">
            </div>
            <div class="col-lg-4 d-lg-block d-md-none d-sm-none d-none">
                <ul class="row offset-lg-1">
                    <li class="col-lg-6">
                        <a class="<?php echo ($this->action == 'home' && $this->module == 'static') ? 'active' : '';?>"
                           href="<?php echo $this->url(['controller' => 'index', 'action' => 'index', 'module'=> 'default'], 'default', true);?>">Главная</a>
                    </li>
                    <li class="col-lg-6">
                        <a class="<?php echo ($this->alias == 'contacts' && $this->module == 'static') ? 'active' : '';?>"
                           href="<?php echo $this->url(array('alias' => 'contacts'), '/static/index/index');?>">Контакты</a>
                    </li>
                    <li class="col-lg-6">
                        <a class="<?php echo ($this->module == 'services') ? 'active' : '';?>"
                           href="<?php echo $this->url(['controller' => 'index', 'action' => 'index', 'module'=> 'services', 'id' => $this->defaultServicesCategory[0]['id']], 'default', true);?>">Услуги</a>
                    </li>
                    <li class="col-lg-6">
                        <a class="<?php echo ($this->module == 'portfolio') ? 'active' : '';?>"
                           href="<?php echo $this->url(['controller' => 'index', 'action' => 'index', 'module'=> 'portfolio'], 'default', true);?>">Портфолио</a>
                    </li>
                    <li class="col-lg-6">
                        <a class="<?php echo ($this->alias == 'about' && $this->module == 'static') ? 'active' : '';?>"
                           href="<?php echo $this->url(array('alias' => 'about'), '/static/index/index');?>">О Компании</a>
                    </li>
                    <li class="col-lg-6">
                        <a class="<?php echo ($this->module == 'reviews') ? 'active' : '';?>"
                           href="<?php echo $this->url(['controller' => 'index', 'action' => 'index', 'module'=> 'reviews', 'reviewsCount' => 9], 'default', true);?>">Отзывы</a>
                    </li>
                </ul>
            </div>
            <div class="offset-lg-0 col-lg-3 offset-md-0 col-md-4 offset-sm-0 col-sm-6 offset-1 col-11">
                <div class="title">Контакты</div>
                <div id="contact_info">
                    <div><i class="fas fa-phone fa-flip-horizontal"></i><span><?php echo $this->data['phone'];?></span></div>
                    <div><i class="fas fa-map-marker-alt"></i><span><?php echo $this->data['address'];?></span></div>
                </div>
            </div>
            <div class="offset-lg-0 col-lg-3 offset-md-0 col-md-4 offset-sm-0 col-sm-6 offset-1 col-11">
                <div class="title">Соц. сети</div>
                <div id="socials">
                    <div><a><i class="fab fa-vk"></i><?php echo $this->vk[0]['url'];?></a></div>
                    <div><a><i class="fab fa-instagram"></i><?php echo $this->instagram[0]['url'];?></a></div>
                    <div><a><i class="fab fa-facebook-f"></i><?php echo $this->facebook[0]['url'];?></a></div>
                </div>
            </div>
        </div>
    </div>
    <div id="copyright"><i class="fas fa-star"></i>ВЕБ-СТУДИЯ ITROCKS 2018</div>
</footer>