<section id="promoblock">
    <div class="container">
        <div id="promotext" class="offset-lg-2 col-lg-8 offset-md-1 col-md-10 col-sm-12 col-12">Доверьте ремонт профессионалам</div>
        <div id="hint" class="offset-lg-3 col-lg-6">а не нам</div>
        <div id="callus_form" class="offset-lg-3 col-lg-6 offset-md-2 col-md-8 col-sm-12 col-12">
            <div class="formheader">
                <b>Оставьте заявку</b>
                <small><small>наш менеджер перезвонит вам в течении 20 минут</small></small>
            </div>
            <form class="col-12" method="post" action="">
                <div class="form-group row">
                    <label for="nameInput" class="col-2"><i class="fas fa-user"></i></label>
                    <input type="text" class="form-control col-10" id="nameInput" aria-describedby="name" placeholder="Имя" required>
                </div>
                <div class="form-group row">
                    <label for="phoneInput" class="col-2"><i class="fas fa-phone fa-flip-horizontal"></i></label>
                    <input type="text" class="form-control col-10" id="phoneInput" placeholder="Телефон" required>
                </div>
                <button id="callus_button" type="submit" class="main_button">Отправить</button>
            </form>
        </div>
    </div>
</section>