<div class="alert margin alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>Внимание!</strong> 
    <?php echo $this->translate('deletingCategoryWarningMessage'); ?>
</div>

<div class="page-header">
    <div class="page-title">
        <h5><?php echo $this->translate('deletingCategoryPageTitle'); ?></h5> 
        <span><?php echo $this->translate('deletingCategoryPageTitleSpan'); ?></span>
    </div>
</div>

<h5 class="widget-name"></h5>

<div class="widget row-fluid">
    <div class="well span8">
        <div class="form-overflow">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>