<!-- Page header -->
<div class="page-header">
    <div class="page-title">
        <h5>
            <?php echo $this->translate('sliderForm'); ?>
        </h5>
        <span></span>
    </div>
</div>
<!-- /page header -->
<?php if (isset($this->error)) : ?>
    <div class="alert alert-error alert-block" style="margin-top: 16px;">
        <button type="button" class="close icon-close" data-dismiss="alert">×</button>
        <h6>Ошибка!</h6>
        <?php echo $this->error;?>
    </div>
<?php endif;?>

<h5 class="widget-name"></h5>

<!-- Media datatable Last Orders -->
<div class="widget row-fluid">
    <div class="well span12">
        <div class="form-overflow">
            <?php echo $this->form; ?>
            <div style="padding-left: 10px;">Оптимальные размеры изображения: 1020x312 пикселей.</div>
        </div>
    </div>
</div>
<!-- /media datatable -->
